sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - secure: AaTeRG3kL/LeMOcMgul08EUBM7Kdtrkz9EAGPauKdxXbxggP0j5SxN8ciYxc8CiVni0CYJofW07YjG6tXqhvHeMINHx8Q+5KUUfiLwNrLgl1sMkh7vPR9EA5Z1Y8Nz4N1Qt7zxpqWKPHUsjUNFWxP2TPHEq2FEOGeKbsI7GOYas=
    - secure: S5agbWaWSLgbujsVhZB9WkCAM0ris8uh9hPnspYw48bolkMhknJ7JxOWGV4rOcJ52kdOgifFRE9XYi65RFLL8zuaZDBU2zFoXO3fpatziYEiIWnxVrkogw1pnh/FeRnrUld+QDykFyUcfSGdFRw5R5FuZHrxe+Q5bHfiEjh4hlE=
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - composer self-update
  - composer install
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh mail $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable mail
  - npm install -g npm@latest

before_script:
  - cd apps/mail
  - npm install --deps
  - cd js
  - npm install --deps
  - cd ..

script:
  # Test lint
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Test jshint
  - npm test
 
  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable8"
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable8.1"
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable7"

  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true
